### PR TITLE
Improve text readabilty and remove some unneeded anger

### PR DESCRIPTION
**Pull request by Mysterius79**
some people just can't use the puter

### CODE REVIEW

**Comment by Tevtongermany** [comment]
Dude, you aren't even in the Fortnite porting community

**Comment by Tevtongermany** [comment]
just no

**Comment by Mysterius79** [comment]
I would like to know why, since this doesn't change the content of the QA; it just changes the overall readability from annoyed 13 year old to somebody actually wanting to help

**Comment by Tevtongermany** [comment]
There is no roughness/specular value and you would know it if you where in the discord server

**Comment by Mysterius79** [comment]
If that is all just propose the changes instead of just closing the pr

**Comment by Mysterius79** [comment]
> There is no roughness/specular value and you would know it if you where in the discord server or if you used Fortnite porting for once

Having used it now I still think that saying value is more accurate than saying switch since it is a value that can only be 0 or 1, and also it could be caused by the max roughness being set too low

**Pull request closed without merging**
